Repository scalaz/scalaz, pull requests merged in 2018-06, with the labels that each got.

#1841 Remove guideline for order of type parameters in classes
  CONTRIBUTING.md
Labels: scalaz7

#1846 silencer: 0.6 -> 1.0, kind-projector: 0.9.6 -> 0.9.7
  build.sbt
  project/ScalazBuild.scala
Labels: scalaz8

#1848 disable BackgroundRunPlugin. for avoid invoke jvm main
  build.sbt
Labels: scalaz7

#1800 Monad transformers switch type
  core/src/main/scala/scalaz/EitherT.scala
  core/src/main/scala/scalaz/IndexedContsT.scala
  core/src/main/scala/scalaz/Kleisli.scala
  core/src/main/scala/scalaz/LazyOptionT.scala
  core/src/main/scala/scalaz/MaybeT.scala
  core/src/main/scala/scalaz/OptionT.scala
  core/src/main/scala/scalaz/ReaderWriterStateT.scala
  core/src/main/scala/scalaz/StateT.scala
  core/src/main/scala/scalaz/Unapply.scala
  core/src/main/scala/scalaz/UnwriterT.scala
  core/src/main/scala/scalaz/WriterT.scala
  core/src/main/scala/scalaz/package.scala
  core/src/main/scala/scalaz/syntax/ContTOps.scala
  core/src/main/scala/scalaz/syntax/KleisliOps.scala
  effect/src/main/scala/scalaz/effect/LiftIO.scala
  effect/src/main/scala/scalaz/effect/MonadIO.scala
  example/src/main/scala/scalaz/example/ContTUsage.scala
  example/src/main/scala/scalaz/example/ReaderWriterStateTUsage.scala
  example/src/main/scala/scalaz/example/UnapplyInference.scala
  example/src/main/scala/scalaz/example/transformers/typecheck/TypeCheckerWithExplicitTypes_MonadTransformers.scala
  scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala
  tests/src/test/scala/scalaz/EitherTTest.scala
  tests/src/test/scala/scalaz/IndexedContsTTest.scala
  tests/src/test/scala/scalaz/MonadErrorTest.scala
  tests/src/test/scala/scalaz/ReaderWriterStateTTest.scala
  tests/src/test/scala/scalaz/WriterTTest.scala
Labels: scalaz7

#1838 Swap StateT type parameters
  core/src/main/scala/scalaz/Bitraverse.scala
  core/src/main/scala/scalaz/Kleisli.scala
  core/src/main/scala/scalaz/NullResult.scala
  core/src/main/scala/scalaz/ReaderWriterStateT.scala
  core/src/main/scala/scalaz/StateT.scala
  core/src/main/scala/scalaz/Traverse.scala
  core/src/main/scala/scalaz/package.scala
  core/src/main/scala/scalaz/std/List.scala
  core/src/main/scala/scalaz/std/Vector.scala
  core/src/main/scala/scalaz/syntax/StateOps.scala
  effect/src/main/scala/scalaz/effect/LiftIO.scala
  effect/src/main/scala/scalaz/effect/MonadIO.scala
  scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala
  tests/src/test/scala/scalaz/StateTTest.scala
Labels: scalaz7

#1851 Cord v2
  base/shared/src/main/scala/scalaz/core/void.scala
  base/shared/src/main/scala/scalaz/data/Cord.scala
  base/shared/src/main/scala/scalaz/data/amaybe.scala
  base/shared/src/main/scala/scalaz/data/amaybe2.scala
  base/shared/src/main/scala/scalaz/data/const.scala
  base/shared/src/main/scala/scalaz/data/disjunction.scala
  base/shared/src/main/scala/scalaz/data/identity.scala
  base/shared/src/main/scala/scalaz/data/ilist.scala
  base/shared/src/main/scala/scalaz/data/maybe.scala
  base/shared/src/main/scala/scalaz/data/maybe2.scala
  base/shared/src/main/scala/scalaz/data/package.scala
  base/shared/src/main/scala/scalaz/data/these.scala
  base/shared/src/main/scala/scalaz/debug/debug.scala
  base/shared/src/main/scala/scalaz/std/utils.scala
  base/shared/src/test/scala/DebugInterpolatorTest.scala
  base/shared/src/test/scala/SyntaxResolutionTest.scala
  benchmarks/src/main/scala/scalaz/data/StringBalancedConcatFoldBenchmark.scala
  benchmarks/src/main/scala/scalaz/data/StringLeftConcatFoldBenchmark.scala
  benchmarks/src/main/scala/scalaz/data/StringRightConcatFoldBenchmark.scala
  build.sbt
  example/src/main/tut/std/Either.md
  example/src/main/tut/typeclass/Debug.md
  example/src/main/tut/typeclass/index.md
  std/shared/src/main/scala/Either.scala
  std/shared/src/main/scala/Option.scala
  std/shared/src/main/scala/collection/List.scala
Labels: scalaz8

#1849 Add README, expand welcome page
  README.md
  build.sbt
  example/src/main/tut/index.md
  project/plugins.sbt
Labels: documentation, scalaz8

#1853 Remove some dubious re-exports from the scalaz package object.
  base/shared/src/main/scala/scalaz/core/void.scala
  base/shared/src/main/scala/scalaz/ct/choice.scala
  base/shared/src/main/scala/scalaz/ct/iso.scala
  base/shared/src/main/scala/scalaz/ct/kleisli.scala
  base/shared/src/main/scala/scalaz/ct/strong.scala
  base/shared/src/main/scala/scalaz/data/Cord.scala
  base/shared/src/main/scala/scalaz/data/disjunction.scala
  base/shared/src/main/scala/scalaz/data/these.scala
  base/shared/src/main/scala/scalaz/package.scala
  base/shared/src/main/scala/scalaz/prelude.scala
  base/shared/src/main/scala/scalaz/types/as.scala
  base/shared/src/main/scala/scalaz/types/is.scala
  base/shared/src/main/scala/scalaz/types/leibniz.scala
  base/shared/src/main/scala/scalaz/types/liskov.scala
  effect/jvm/src/main/scala/scalaz/effect/RTS.scala
  effect/jvm/src/main/scala/scalaz/effect/SafeApp.scala
Labels: scalaz8

#1858 Endo/Const/Identity noots.
  base/shared/src/main/scala/scalaz/ct/endo.scala
  base/shared/src/main/scala/scalaz/ct/package.scala
  base/shared/src/main/scala/scalaz/ct/phantom.scala
  base/shared/src/main/scala/scalaz/data/const.scala
  base/shared/src/main/scala/scalaz/data/identity.scala
  base/shared/src/main/scala/scalaz/data/package.scala
  base/shared/src/main/scala/scalaz/prelude.scala
Labels: scalaz8

#1856 Don't provide the ZipList applicative instance for List in the docs.
  example/src/main/tut/ct/Applicative.md
  example/src/main/tut/ct/Monad.md
Labels: scalaz8

#1752 rename show"" -> z"", and use @implicitAmbiguous for more explanatory error messages
  core/src/main/scala-2.11/scalaz/compat.scala
  core/src/main/scala-2.12/scalaz/compat.scala
  core/src/main/scala-2.13/scalaz/compat.scala
  core/src/main/scala/scalaz/Show.scala
  project/build.scala
  tests/src/test/scala/scalaz/SyntaxTest.scala
Labels: scalaz7

#1857 Add Kleisli arrow with operation fusion for imported (impure) functions
  benchmarks/src/main/scala/scalaz/effect/ArrayFillBenchmark.scala
  benchmarks/src/main/scala/scalaz/effect/BubbleSortBenchmarks.scala
  benchmarks/src/main/scala/scalaz/effect/KleisliIOBenchmarks.scala
  effect/shared/src/main/scala/scalaz/effect/IO.scala
  effect/shared/src/main/scala/scalaz/effect/KleisliIO.scala
Labels: scalaz8

#1860 Make Contravariant a subclass of InvariantFunctor
  base/shared/src/main/scala/scalaz/basehierarchy.scala
  base/shared/src/main/scala/scalaz/ct/contravariant.scala
  base/shared/src/main/scala/scalaz/ct/functor.scala
  base/shared/src/main/scala/scalaz/ct/phantom.scala
Labels: scalaz8

#1862 Fix type params in Kleisli.md
  example/src/main/tut/ct/Kleisli.md
Labels: scalaz8

#1813 add LICENSE.txt to all packaged jars. (forward port to 8.0.x)
  LICENSE.txt
  build.sbt
  project/ScalazBuild.scala
Labels: scalaz8

#1864 fix -Ywarn-unused scalacOptions
  project/build.scala
Labels: scalaz7

#1865 Fix type inference on These#fold
  base/shared/src/main/scala/scalaz/data/these.scala
  example/src/main/tut/data/These.md
Labels: scalaz8

#1869 enable tests for Scala 2.13.0-M4
  .travis.yml
  project/build.scala
  scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala
Labels: scalaz7

#1880 Void syntax resolution test
  base/shared/src/test/scala/SyntaxResolutionTest.scala
Labels: scalaz8

#1871 rename Compose -> Semicategory, and make Compose the Haskell one
  base/shared/src/main/scala/scalaz/basehierarchy.scala
  base/shared/src/main/scala/scalaz/ct/category.scala
  base/shared/src/main/scala/scalaz/ct/compose.scala
  base/shared/src/main/scala/scalaz/ct/endo.scala
  base/shared/src/main/scala/scalaz/ct/kleisli.scala
  base/shared/src/main/scala/scalaz/ct/package.scala
  base/shared/src/main/scala/scalaz/ct/semicategory.scala
  base/shared/src/main/scala/scalaz/data/acatenable1.scala
  base/shared/src/main/scala/scalaz/data/alist.scala
  base/shared/src/main/scala/scalaz/data/alist1.scala
  base/shared/src/main/scala/scalaz/data/balanced.scala
  base/shared/src/main/scala/scalaz/data/package.scala
  base/shared/src/main/scala/scalaz/prelude.scala
  base/shared/src/test/scala/SyntaxResolutionTest.scala
  example/src/main/resources/microsite/data/menu.yml
  example/src/main/tut/ct/Compose.md
  example/src/main/tut/ct/Kleisli.md
  example/src/main/tut/ct/Semicategory.md
Labels: scalaz8

#1874 Add dependency on ZIO and remove effect module
  base/shared/src/main/scala/scalaz/core/io.scala
  base/shared/src/main/scala/scalaz/prelude.scala
  base/shared/src/test/scala/CovariantResolutionTest.scala
  benchmarks/src/main/scala/scalaz/effect/ArrayFillBenchmark.scala
  benchmarks/src/main/scala/scalaz/effect/BubbleSortBenchmarks.scala
  benchmarks/src/main/scala/scalaz/effect/IOBenchmarks.scala
  benchmarks/src/main/scala/scalaz/effect/IODeepAttemptBenchmark.scala
  benchmarks/src/main/scala/scalaz/effect/IODeepFlatMapBenchmark.scala
  benchmarks/src/main/scala/scalaz/effect/IOLeftBindBenchmark.scala
  benchmarks/src/main/scala/scalaz/effect/IOMapBenchmark.scala
  benchmarks/src/main/scala/scalaz/effect/IONarrowFlatMapBenchmark.scala
  benchmarks/src/main/scala/scalaz/effect/IOShallowAttemptBenchmark.scala
  benchmarks/src/main/scala/scalaz/effect/KleisliIOBenchmarks.scala
  build.sbt
  effect/README.md
  effect/js/src/main/scala/scalaz/effect/SafeApp.scala
  effect/jvm/src/main/scala/scalaz/effect/RTS.scala
  effect/jvm/src/main/scala/scalaz/effect/SafeApp.scala
  effect/jvm/src/main/scala/scalaz/effect/console/package.scala
  effect/jvm/src/test/scala/scalaz/effect/IOInstancesSpec.scala
  effect/jvm/src/test/scala/scalaz/effect/IOQueueSpec.scala
  effect/jvm/src/test/scala/scalaz/effect/IORefSpec.scala
  effect/jvm/src/test/scala/scalaz/effect/KleisliIOSpec.scala
  effect/jvm/src/test/scala/scalaz/effect/PromiseSpec.scala
  effect/jvm/src/test/scala/scalaz/effect/RTSSpec.scala
  effect/jvm/src/test/scala/scalaz/effect/generator/GenIO.scala
  effect/shared/src/main/scala/scalaz/effect/Async.scala
  effect/shared/src/main/scala/scalaz/effect/Errors.scala
  effect/shared/src/main/scala/scalaz/effect/ExitResult.scala
  effect/shared/src/main/scala/scalaz/effect/Fiber.scala
  effect/shared/src/main/scala/scalaz/effect/IO.scala
  effect/shared/src/main/scala/scalaz/effect/IOInstances.scala
  effect/shared/src/main/scala/scalaz/effect/IOQueue.scala
  effect/shared/src/main/scala/scalaz/effect/IORef.scala
  effect/shared/src/main/scala/scalaz/effect/KleisliIO.scala
  effect/shared/src/main/scala/scalaz/effect/Promise.scala
  effect/shared/src/main/scala/scalaz/effect/package.scala
Labels: scalaz8

#1837 Free Monads
  core/src/main/scala/scalaz/MonadError.scala
  core/src/main/scala/scalaz/MonadListen.scala
  core/src/main/scala/scalaz/MonadPlus.scala
  core/src/main/scala/scalaz/MonadReader.scala
  core/src/main/scala/scalaz/MonadState.scala
  core/src/main/scala/scalaz/MonadTell.scala
  example/src/main/scala/scalaz/example/FreeMonadsUsage.scala
Labels: scalaz7

#1881 [scalaz-deriving] Decidable and Alt
  core/src/main/scala/scalaz/Alt.scala
  core/src/main/scala/scalaz/Applicative.scala
  core/src/main/scala/scalaz/ApplicativeDivisible.scala
  core/src/main/scala/scalaz/ApplicativePlus.scala
  core/src/main/scala/scalaz/Apply.scala
  core/src/main/scala/scalaz/ApplyDivide.scala
  core/src/main/scala/scalaz/Coapplicative.scala
  core/src/main/scala/scalaz/CoapplicativeCodivide.scala
  core/src/main/scala/scalaz/Codivide.scala
  core/src/main/scala/scalaz/Const.scala
  core/src/main/scala/scalaz/ContravariantDerives.scala
  core/src/main/scala/scalaz/CovariantDerives.scala
  core/src/main/scala/scalaz/Decidable.scala
  core/src/main/scala/scalaz/Derives.scala
  core/src/main/scala/scalaz/Divide.scala
  core/src/main/scala/scalaz/Divisible.scala
  core/src/main/scala/scalaz/Equal.scala
  core/src/main/scala/scalaz/package.scala
  core/src/main/scala/scalaz/syntax/AltSyntax.scala
  core/src/main/scala/scalaz/syntax/ApplicativeDivisibleSyntax.scala
  core/src/main/scala/scalaz/syntax/ApplicativeSyntax.scala
  core/src/main/scala/scalaz/syntax/ApplyDivideSyntax.scala
  core/src/main/scala/scalaz/syntax/ApplySyntax.scala
  core/src/main/scala/scalaz/syntax/CoapplicativeCodivideSyntax.scala
  core/src/main/scala/scalaz/syntax/CoapplicativeSyntax.scala
  core/src/main/scala/scalaz/syntax/CodivideSyntax.scala
  core/src/main/scala/scalaz/syntax/ContravariantDerivesSyntax.scala
  core/src/main/scala/scalaz/syntax/CovariantDerivesSyntax.scala
  core/src/main/scala/scalaz/syntax/DecidableSyntax.scala
  core/src/main/scala/scalaz/syntax/DerivesSyntax.scala
  core/src/main/scala/scalaz/syntax/DivideSyntax.scala
  core/src/main/scala/scalaz/syntax/DivisibleSyntax.scala
  core/src/main/scala/scalaz/syntax/Syntax.scala
  project/GenTypeClass.scala
  scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala
  tests/src/test/scala/examples/adts.scala
  tests/src/test/scala/scalaz/DecidableSpec.scala
  tests/src/test/scala/scalaz/Default.scala
Labels: scalaz7

#1843 Inject.instance
  core/src/main/scala/scalaz/Inject.scala
Labels: scalaz7

#1891 convenient methods and type aliases for parallelism
  core/src/main/scala-2.12+/scalaz/ApplicativeParent.scala
  core/src/main/scala/scalaz/Applicative.scala
  core/src/main/scala/scalaz/Apply.scala
  core/src/main/scala/scalaz/Isomorphism.scala
  core/src/main/scala/scalaz/Validation.scala
  core/src/main/scala/scalaz/package.scala
  core/src/main/scala/scalaz/syntax/ApplicativeBuilder.scala
  core/src/main/scala/scalaz/syntax/MonadErrorSyntax.scala
  core/src/main/scala/scalaz/syntax/TraverseSyntax.scala
  example/src/main/scala/scalaz/example/ApplyUsage.scala
Labels: scalaz7

#1895 Missing IList API
  base/shared/src/main/scala/scalaz/ct/kleisli.scala
  base/shared/src/main/scala/scalaz/data/ilist.scala
  base/shared/src/main/scala/scalaz/prelude.scala
  microsite/src/main/tut/ct/Kleisli.md
Labels: scalaz8

#1896 instances: Decidable[Order], Alt[Maybe]
  core/src/main/scala/scalaz/Maybe.scala
  core/src/main/scala/scalaz/Order.scala
Labels: scalaz7

#1894 More direct / efficient Monad.apply2
  core/src/main/scala/scalaz/Bind.scala
Labels: scalaz7

#1901 Add identity traversable, foldable and monoid instances
  base/shared/src/main/scala/scalaz/data/identity.scala
Labels: scalaz8

#1902 Add contravariant syntax
  base/shared/src/main/scala/scalaz/ct/contravariant.scala
  base/shared/src/main/scala/scalaz/prelude.scala
Labels: scalaz8
