Repository scalaz/scalaz, pull requests merged in 2018-09, with the labels that each got.

#1963 Alist1 tests
  base/shared/src/main/scala/scalaz/data/acatenable1.scala
  base/shared/src/main/scala/scalaz/data/alist.scala
  base/shared/src/main/scala/scalaz/data/alist1.scala
  base/shared/src/main/scala/scalaz/data/balanced.scala
  base/shared/src/main/scala/scalaz/data/biconst.scala
  base/shared/src/main/scala/scalaz/data/forall3.scala
  base/shared/src/main/scala/scalaz/data/package.scala
  project/build.properties
  tests/src/main/scala/scalaz/tests/ACatenable1Tests.scala
  tests/src/main/scala/scalaz/tests/AList1Tests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
Labels: scalaz8

#1972 Testz 0.0.5
  base/shared/src/main/scala/scalaz/data/amaybe.scala
  base/shared/src/main/scala/scalaz/data/amaybe2.scala
  base/shared/src/main/scala/scalaz/tc/debug.scala
  base/shared/src/main/scala/scalaz/tc/unfoldable1.scala
  build.sbt
  microsite/src/main/tut/data/Maybe2.md
  tests/src/main/scala/scalaz/tests/ACatenable1Tests.scala
  tests/src/main/scala/scalaz/tests/AFixTests.scala
  tests/src/main/scala/scalaz/tests/AList1Tests.scala
  tests/src/main/scala/scalaz/tests/AMaybe2Tests.scala
  tests/src/main/scala/scalaz/tests/AMaybeTests.scala
  tests/src/main/scala/scalaz/tests/DebugInterpolatorTest.scala
  tests/src/main/scala/scalaz/tests/DoubleTests.scala
  tests/src/main/scala/scalaz/tests/IListTests.scala
  tests/src/main/scala/scalaz/tests/SMapTests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
  tests/src/main/scala/scalaz/tests/z.scala
Labels: scalaz8

#1368 Isomorphic between Future and ContT
  concurrent/src/main/scala/scalaz/concurrent/Future.scala
Labels: scalaz7

#1817 A quick and dirty Tree.
  base/shared/src/main/scala/scalaz/data/package.scala
  base/shared/src/main/scala/scalaz/data/tree.scala
  microsite/src/main/resources/microsite/data/menu.yml
  microsite/src/main/tut/data/FixFree.md
Labels: scalaz8

#1970 Tests for Const (mostly copypasta from IListTests)
  tests/src/main/scala/scalaz/tests/ConstTests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
Labels: scalaz8

#1923 [1185] More Alt instances
  core/src/main/scala/scalaz/CorecursiveList.scala
  core/src/main/scala/scalaz/DList.scala
  core/src/main/scala/scalaz/Dequeue.scala
  core/src/main/scala/scalaz/Either.scala
  core/src/main/scala/scalaz/EitherT.scala
  core/src/main/scala/scalaz/EphemeralStream.scala
  core/src/main/scala/scalaz/FingerTree.scala
  core/src/main/scala/scalaz/FreeT.scala
  core/src/main/scala/scalaz/IList.scala
  core/src/main/scala/scalaz/IndexedContsT.scala
  core/src/main/scala/scalaz/Kleisli.scala
  core/src/main/scala/scalaz/LazyEither.scala
  core/src/main/scala/scalaz/LazyEitherT.scala
  core/src/main/scala/scalaz/LazyOption.scala
  core/src/main/scala/scalaz/LazyOptionT.scala
  core/src/main/scala/scalaz/ListT.scala
  core/src/main/scala/scalaz/NonEmptyList.scala
  core/src/main/scala/scalaz/NullResult.scala
  core/src/main/scala/scalaz/OneAnd.scala
  core/src/main/scala/scalaz/OptionT.scala
  core/src/main/scala/scalaz/Validation.scala
  core/src/main/scala/scalaz/std/List.scala
  core/src/main/scala/scalaz/std/Option.scala
  core/src/main/scala/scalaz/std/Stream.scala
  core/src/main/scala/scalaz/std/Vector.scala
  tests/src/test/scala/scalaz/CorecursiveListTest.scala
  tests/src/test/scala/scalaz/DListTest.scala
  tests/src/test/scala/scalaz/DequeueTest.scala
  tests/src/test/scala/scalaz/EitherTTest.scala
  tests/src/test/scala/scalaz/EphemeralStreamTest.scala
  tests/src/test/scala/scalaz/FingerTreeTest.scala
  tests/src/test/scala/scalaz/FreeTTest.scala
  tests/src/test/scala/scalaz/IListTest.scala
  tests/src/test/scala/scalaz/IndexedContsTTest.scala
  tests/src/test/scala/scalaz/KleisliTest.scala
  tests/src/test/scala/scalaz/LazyEitherTTest.scala
  tests/src/test/scala/scalaz/LazyEitherTest.scala
  tests/src/test/scala/scalaz/LazyOptionTTest.scala
  tests/src/test/scala/scalaz/LazyOptionTest.scala
  tests/src/test/scala/scalaz/ListTTest.scala
  tests/src/test/scala/scalaz/NonEmptyListTest.scala
  tests/src/test/scala/scalaz/OneAndTest.scala
  tests/src/test/scala/scalaz/OptionTTest.scala
  tests/src/test/scala/scalaz/ValidationTest.scala
  tests/src/test/scala/scalaz/std/ListTest.scala
  tests/src/test/scala/scalaz/std/OptionTest.scala
  tests/src/test/scala/scalaz/std/StreamTest.scala
  tests/src/test/scala/scalaz/std/VectorTest.scala
Labels: scalaz7

#1989 Use a stable ZIO release, update instances for it, rudimentary IO tests
  base/shared/src/main/scala/scalaz/tc/applicative.scala
  base/shared/src/main/scala/scalaz/tc/monoid.scala
  build.sbt
  tests/src/main/scala/scalaz/tests/IOTests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
Labels: scalaz8

#1978 Dimap and lift as methods on Kleisli
  base/shared/src/main/scala/scalaz/data/kleisli.scala
Labels: scalaz8

#1979 Ordering instances/tests, clearer test section names
  base/shared/src/main/scala/scalaz/data/ordering.scala
  base/shared/src/main/scala/scalaz/tc/eq.scala
  tests/src/main/scala/scalaz/tests/ACatenable1Tests.scala
  tests/src/main/scala/scalaz/tests/AList1Tests.scala
  tests/src/main/scala/scalaz/tests/AMaybeTests.scala
  tests/src/main/scala/scalaz/tests/ConstTests.scala
  tests/src/main/scala/scalaz/tests/DoubleTests.scala
  tests/src/main/scala/scalaz/tests/IListTests.scala
  tests/src/main/scala/scalaz/tests/OrderingTests.scala
  tests/src/main/scala/scalaz/tests/SMapTests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
Labels: scalaz8

#1988 Adding prochoice to all syntax
  core/src/main/scala/scalaz/syntax/Syntax.scala
Labels: scalaz7

#1990 Sufficiency annotations.
  base/shared/src/main/scala/scalaz/data/biconst.scala
  base/shared/src/main/scala/scalaz/data/compose.scala
  base/shared/src/main/scala/scalaz/data/const.scala
  base/shared/src/main/scala/scalaz/data/disjunction.scala
  base/shared/src/main/scala/scalaz/data/ilist.scala
  base/shared/src/main/scala/scalaz/data/kleisli.scala
  base/shared/src/main/scala/scalaz/data/maybe.scala
  base/shared/src/main/scala/scalaz/data/maybe2.scala
  base/shared/src/main/scala/scalaz/data/these.scala
  base/shared/src/main/scala/scalaz/data/tree.scala
  base/shared/src/main/scala/scalaz/tc/applicative.scala
  base/shared/src/main/scala/scalaz/tc/apply.scala
  base/shared/src/main/scala/scalaz/tc/bifunctor.scala
  base/shared/src/main/scala/scalaz/tc/bind.scala
  base/shared/src/main/scala/scalaz/tc/choice.scala
  base/shared/src/main/scala/scalaz/tc/cobind.scala
  base/shared/src/main/scala/scalaz/tc/comonad.scala
  base/shared/src/main/scala/scalaz/tc/contravariant.scala
  base/shared/src/main/scala/scalaz/tc/debug.scala
  base/shared/src/main/scala/scalaz/tc/eq.scala
  base/shared/src/main/scala/scalaz/tc/foldable.scala
  base/shared/src/main/scala/scalaz/tc/functor.scala
  base/shared/src/main/scala/scalaz/tc/invariantfunctor.scala
  base/shared/src/main/scala/scalaz/tc/monad.scala
  base/shared/src/main/scala/scalaz/tc/ord.scala
  base/shared/src/main/scala/scalaz/tc/phantom.scala
  base/shared/src/main/scala/scalaz/tc/profunctor.scala
  base/shared/src/main/scala/scalaz/tc/semicategory.scala
  base/shared/src/main/scala/scalaz/tc/semigroup.scala
  base/shared/src/main/scala/scalaz/tc/strong.scala
  base/shared/src/main/scala/scalaz/tc/traversable.scala
  meta/shared/src/main/scala/scalaz/ops/Ops.scala
  microsite/src/main/tut/typeclass/Applicative.md
  microsite/src/main/tut/typeclass/Apply.md
  microsite/src/main/tut/typeclass/Bifunctor.md
  microsite/src/main/tut/typeclass/Monad.md
  project/ScalazBuild.scala
Labels: scalaz8

#1992 Benchmark tests
  benchmarks/src/main/scala/scalaz/tests/TestBenchmark.scala
  build.sbt
Labels: scalaz8

#1996 Update site link to real URL
  README.md
Labels: documentation, scalaz8

#1999 Fixing unused imports in TestBenchmark
  benchmarks/src/main/scala/scalaz/tests/TestBenchmark.scala
Labels: scalaz8

#2007 Remove Eq.never
  base/shared/src/main/scala/scalaz/tc/eq.scala
Labels: scalaz8
