Repository scalaz/scalaz, pull requests merged in 2018-08, with the labels that each got.

#1875 Make Traversables short-circuiting and stack-safe
  core/src/main/scala/scalaz/EphemeralStream.scala
  core/src/main/scala/scalaz/IList.scala
  core/src/main/scala/scalaz/NonEmptyList.scala
  core/src/main/scala/scalaz/Reducer.scala
  core/src/main/scala/scalaz/std/Stream.scala
  tests/src/test/scala/scalaz/TraverseTest.scala
Labels: scalaz7

#1938 Align with latest updates in zio
  base/shared/src/main/scala/scalaz/tc/applicative.scala
  base/shared/src/main/scala/scalaz/tc/monoid.scala
Labels: scalaz8

#1935 Add Unfoldable
  base/shared/src/main/scala/scalaz/data/ilist.scala
  base/shared/src/main/scala/scalaz/tc/package.scala
  base/shared/src/main/scala/scalaz/tc/unfoldable.scala
  microsite/src/main/resources/microsite/data/menu.yml
  microsite/src/main/tut/typeclass/Unfoldable.md
Labels: scalaz8

#1934 Add some laws
  build.sbt
  laws/shared/src/main/scala/scalaz/laws/ActionLaws.scala
  laws/shared/src/main/scala/scalaz/laws/HomomorphismLaws.scala
  laws/shared/src/main/scala/scalaz/laws/TypeclassLaws.scala
Labels: scalaz8

#1944 fix some typo
  concurrent/src/main/scala/scalaz/concurrent/Task.scala
  core/src/main/scala/scalaz/Cord.scala
  example/src/main/scala/scalaz/example/FoldableUsage.scala
  example/src/main/scala/scalaz/example/KleisliUsage.scala
  example/src/main/scala/scalaz/example/ReaderWriterStateTUsage.scala
  example/src/main/scala/scalaz/example/TagUsage.scala
Labels: scalaz7

#1936 Laws 2
  base/shared/src/test/scala/DebugInterpolatorTest.scala
  laws/shared/src/main/scala/scalaz/laws/FunctorLaws.scala
  laws/shared/src/main/scala/scalaz/laws/HomomorphismLaws.scala
  laws/shared/src/main/scala/scalaz/laws/TypeclassLaws.scala
  project/ScalazBuild.scala
Labels: scalaz8

#1943 Debug tests
  base/shared/src/main/scala/scalaz/data/Cord.scala
  base/shared/src/test/scala/DebugInterpolatorTest.scala
  tests/src/main/scala/scalaz/tests/DebugInterpolatorTest.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
Labels: scalaz8

#1953 Add more IList tests
  base/shared/src/main/scala/scalaz/data/compose.scala
  base/shared/src/main/scala/scalaz/data/identity.scala
  base/shared/src/main/scala/scalaz/data/ilist.scala
  base/shared/src/main/scala/scalaz/data/maybe.scala
  base/shared/src/main/scala/scalaz/data/maybe2.scala
  base/shared/src/main/scala/scalaz/data/these.scala
  base/shared/src/main/scala/scalaz/tc/foldable.scala
  meta/shared/src/main/scala/scalaz/meta/Ops.scala
  tests/src/main/scala/scalaz/tests/IListTests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
Labels: scalaz8

#1958 Optimise Apply[{ Either, \/ }].apply2
  core/src/main/scala/scalaz/Either.scala
  core/src/main/scala/scalaz/IList.scala
  core/src/main/scala/scalaz/std/Either.scala
  tests/src/test/scala/scalaz/IListTest.scala
Labels: scalaz7

#1952 Fix typos detected by github.com/client9/misspell
  README.md
  example/src/main/scala/scalaz/example/ApplyUsage.scala
  example/src/main/scala/scalaz/example/WordCount.scala
  tests/jvm/src/test/scala/scalaz/concurrent/ConcurrentTest.scala
Labels: scalaz7

#1955 Place microsite in folder
  build.sbt
Labels: documentation, scalaz7

#1960 Tests for ACatenable1
  .jvmopts
  .travis.yml
  base/shared/src/main/scala/scalaz/data/acatenable1.scala
  base/shared/src/main/scala/scalaz/data/biconst.scala
  base/shared/src/main/scala/scalaz/data/const.scala
  base/shared/src/main/scala/scalaz/data/package.scala
  base/shared/src/main/scala/scalaz/tc/category.scala
  base/shared/src/main/scala/scalaz/tc/semicategory.scala
  base/shared/src/main/scala/scalaz/tc/semigroup.scala
  tests/src/main/scala/scalaz/tests/ACatenable1Tests.scala
  tests/src/main/scala/scalaz/tests/IListTests.scala
  tests/src/main/scala/scalaz/tests/SMapTests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
  tests/src/main/scala/scalaz/tests/z.scala
Labels: scalaz8

#1957 Fixed Eq[Double].
  base/shared/src/main/scala/scalaz/data/ilist.scala
  base/shared/src/main/scala/scalaz/tc/eq.scala
  tests/src/main/scala/scalaz/tests/DoubleTests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
Labels: scalaz8

#1932 Add more decidable/divisible instances
  core/src/main/scala/scalaz/Kleisli.scala
  core/src/main/scala/scalaz/ListT.scala
  core/src/main/scala/scalaz/OptionT.scala
  core/src/main/scala/scalaz/StateT.scala
  core/src/main/scala/scalaz/WriterT.scala
  tests/src/test/scala/scalaz/KleisliTest.scala
  tests/src/test/scala/scalaz/ListTTest.scala
  tests/src/test/scala/scalaz/OptionTTest.scala
  tests/src/test/scala/scalaz/StateTTest.scala
  tests/src/test/scala/scalaz/WriterTTest.scala
Labels: scalaz7

#1966 Add Unfoldable1, update Unfoldable
  base/shared/src/main/scala/scalaz/data/ilist.scala
  base/shared/src/main/scala/scalaz/tc/package.scala
  base/shared/src/main/scala/scalaz/tc/unfoldable.scala
  base/shared/src/main/scala/scalaz/tc/unfoldable1.scala
  microsite/src/main/resources/microsite/data/menu.yml
  microsite/src/main/tut/typeclass/Unfoldable.md
  microsite/src/main/tut/typeclass/Unfoldable1.md
Labels: scalaz8

#1962 AFix tests, testz update, `show` option
  build.sbt
  tests/src/main/scala/scalaz/tests/AFixTests.scala
  tests/src/main/scala/scalaz/tests/TestMain.scala
Labels: scalaz8

#1947 Law docs
  build.sbt
  laws/shared/src/main/scala/scalaz/laws/TypeclassLaws.scala
  microsite/src/main/resources/microsite/data/menu.yml
  microsite/src/main/tut/typeclass/Applicative.md
  microsite/src/main/tut/typeclass/Apply.md
  microsite/src/main/tut/typeclass/Bifunctor.md
  microsite/src/main/tut/typeclass/Bind.md
  microsite/src/main/tut/typeclass/Category.md
  microsite/src/main/tut/typeclass/Debug.md
  microsite/src/main/tut/typeclass/Eq.md
  microsite/src/main/tut/typeclass/Functor.md
  microsite/src/main/tut/typeclass/Laws.md
  microsite/src/main/tut/typeclass/Monad.md
  microsite/src/main/tut/typeclass/Monoid.md
  microsite/src/main/tut/typeclass/Ord.md
  microsite/src/main/tut/typeclass/Semicategory.md
  microsite/src/main/tut/typeclass/Semigroup.md
  microsite/src/main/tut/typeclass/Unfoldable.md
  microsite/src/main/tut/typeclass/Unfoldable1.md
  tests/src/main/scala/scalaz/tests/DoubleTests.scala
  tests/src/main/scala/scalaz/tests/IListTests.scala
Labels: scalaz8

#1511 Add Zap instance for pairs of Zaps
  core/src/main/scala/scalaz/Zap.scala
Labels: scalaz7
